#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CFG_DIR="${SCRIPT_DIR}/cfg"

printf "Updating system...\n"
"${CFG_DIR}/apt.sh"
printf "\nRemoving folders...\n"
"${CFG_DIR}/folders.sh"
printf "\nInstalling packages...\n"
"${CFG_DIR}/pack.sh"
printf "\nInstalling plugins...\n"
"${CFG_DIR}/plugins.sh"
printf "\nInstalling config files...\n"
"${CFG_DIR}/install.sh"
printf "\nBacking up config files...\n"
"${CFG_DIR}/bak.sh"
printf "\nInstalling color themes...\n"
"${CFG_DIR}/colors.sh"
printf "\nApplying git settings\n"
"${CFG_DIR}/git.sh"
printf "\n__CURRENT COLORS__\n"
"${CFG_DIR}/dircolors.sh"
printf "^^CURRENT COLORS^^\n"
printf "\nDone!\n"
